version: '3'

services:
  backend:
   container_name: ft_transcendence_backend
   build:
    context: ./backend
    dockerfile: src/api/Dockerfile
   ports: 
     - '3000:3000'
   volumes:
     - ./backend/src:/app/nestjs/src
   networks:
     - default

  postgres:
   container_name: ft_transcendence_postgres
   build:
    context: ./backend/
    dockerfile: src/database/Dockerfile
   ports:
     - '5432:5432'
   volumes:
     - /var/lib/postgresql/data
   networks:
     - default
    
  adminer-docker:
   image: adminer:4.8.1
   container_name: ft_transcendence_adminer
   restart: on-failure
   depends_on:
     - postgres
   networks:
     - default
   ports:
     - 8080:8080 

networks:
  default:
    name: ft_transcendence

