version: '3'

services:
  backend:
   container_name: ft_transcendence_backend
   build:
    context: ./backend
    dockerfile: Dockerfile
   ports: 
     - '3000:3000'
   volumes:
     - ./backend/src:/app/nestjs/src

  postgres:
   container_name: ft_transcendence_postgres
   build:
    context: ./database
    dockerfile: Dockerfile
   image: postgres
   environment:
     - POSTGRES_USER=rdas-nev
     - POSTGRES_PASSWORD=inception123
     - POSTGRES_DB=pongdb
   ports:
     - '5432:5432'
   volumes:
     - postgres-data:/var/lib/postgresql/data

networks:
  default:
    name: ft_transcendence

volumes:
  postgres-data:
